#-----------------------------------------------------------------------------
# MARKOV MAKEFILES
#----------------------------------------------------------------------------

all:
	make -C markov_c 
	make -C markov_cpp 
	make -C markov_java

clean:
	make -C markov_c clean
	make -C markov_cpp clean
	make -C markov_java clean
run:
	make -C markov_c run
	make -C markov_cpp run
	make -C markov_java run
